name: JWildTP
main: com.johnymuffin.beta.wildtp.JWildTP
version: 1.0.2
author: JohnyMuffin
description: A plugin to randomly teleport
commands:
  wild:
    description: A command to randomly teleport
    usage: /<command>
    aliases: [random, randomtp, rtp]
permissions:
  jwildtp.wild:
    description: Allows a player to randomly teleport